Replace spaces with tabs

diff --git a/dotenv/bin/git-hooks b/dotenv/bin/git-hooks
--- a/dotenv/bin/git-hooks
+++ b/dotenv/bin/git-hooks
@@ -6,13 +6,13 @@ SUBDIRECTORY_OK=Yes
 require_work_tree
 
 if [[ -z $1 ]]; then
-	echo "Please select a hook to execute."
-	exit 1
+  echo "Please select a hook to execute."
+  exit 1
 fi
 
 if [[ ! -x "$GIT_DIR/hooks/$1" ]]; then
-	echo "Unable to execute hook '$1'."
-	exit 1
+  echo "Unable to execute hook '$1'."
+  exit 1
 fi
 
 "$GIT_DIR/hooks/$1"
diff --git a/dotenv/bin/git-hub-token b/dotenv/bin/git-hub-token
--- a/dotenv/bin/git-hub-token
+++ b/dotenv/bin/git-hub-token
@@ -4,37 +4,37 @@
 
 # if the -n flag is passed in, don't use the local store, just generate a new token
 if [ "$1" != "-n" ]; then
-	# check the environment first
-	if [ -n "$GIT_HUB_API_TOKEN" ]; then
-		echo "$GIT_HUB_API_TOKEN"
-		exit 0
-	fi
-	# then check the gitconfig file
-	EXISTING_TOKEN=$(git config --get github.apitoken)
-	if [ -n "$EXISTING_TOKEN" ]; then
-		echo "$EXISTING_TOKEN"
-		exit 0
-	fi
+  # check the environment first
+  if [ -n "$GIT_HUB_API_TOKEN" ]; then
+    echo "$GIT_HUB_API_TOKEN"
+    exit 0
+  fi
+  # then check the gitconfig file
+  EXISTING_TOKEN=$(git config --get github.apitoken)
+  if [ -n "$EXISTING_TOKEN" ]; then
+    echo "$EXISTING_TOKEN"
+    exit 0
+  fi
 fi
 
 # Generate a token for the following username
 read -p "Github username: " GITHUB_USERNAME
 if [ -z "$GITHUB_USERNAME" ]; then
-	echo "Github username required"
-	exit 1
+  echo "Github username required"
+  exit 1
 fi
 
 HOSTNAME=$(hostname)
 # Grab the app token name, using hostname as the default
 read -p "Github token name ($HOSTNAME): " GITHUB_TOKEN_NAME
 if [ -z "$GITHUB_TOKEN_NAME" ]; then
-	GITHUB_TOKEN_NAME="$HOSTNAME"
+  GITHUB_TOKEN_NAME="$HOSTNAME"
 fi
 
 GITHUB_TOKEN_RESPONSE=$(curl -i https://api.github.com/authorizations -u "$GITHUB_USERNAME" -d '{"scopes":"repo","note":"'$GITHUB_TOKEN_NAME'"}')
 
 if [ -z "$GITHUB_TOKEN_RESPONSE" ]; then
-	exit 1
+  exit 1
 fi
 
 # output the curl request to stderr
@@ -42,7 +42,7 @@ echo $GITHUB_TOKEN_RESPONSE > /dev/stderr
 
 # If the response doesn't contain a token then exit with an error
 if [ -z "$(echo "$GITHUB_TOKEN_RESPONSE" | grep '"token":')" ]; then
-	exit 1
+  exit 1
 fi
 
 # just grab out the token
@@ -52,7 +52,7 @@ echo "$GITHUB_TOKEN"
 
 # Write the token to the user's git config
 if [ "$1" != "-n" ]; then
-	git config --global github.apitoken "$GITHUB_TOKEN"
+  git config --global github.apitoken "$GITHUB_TOKEN"
 fi
 
 exit 0
diff --git a/dotenv/bin/git-track b/dotenv/bin/git-track
--- a/dotenv/bin/git-track
+++ b/dotenv/bin/git-track
@@ -12,13 +12,13 @@ BRANCH=$(git branch | grep '^* ' | sed 's/^* //')
 # no pull requests allowed against master unless -f option is on
 getopt_assert -f:--force "$@"
 if [ $? != 0 ] && [ "$BRANCH" == "master" ]; then
-	echo "Tracking modifications cannot be made on the master branch, override with -f."
-	exit 1
+  echo "Tracking modifications cannot be made on the master branch, override with -f."
+  exit 1
 fi
 
 REMOTE=$(getopt_assert -r:--remote "$@")
 if [ -z "$REMOTE" ]; then
-	REMOTE="origin"
+  REMOTE="origin"
 fi
 
 git config branch.$BRANCH.remote $REMOTE
