git: Retrieve github enterprise token from gitconfig

diff --git a/dotenv/bin/git-hub-pull-request b/dotenv/bin/git-hub-pull-request
--- a/dotenv/bin/git-hub-pull-request
+++ b/dotenv/bin/git-hub-pull-request
@@ -30,25 +30,10 @@ if [[ -z "${UPSTREAM}" ]]; then
   exit 128
 fi
 
-# push this branch to origin first
-git push origin "${BRANCH}"
-BRANCH_EXIT_STATUS=$?
-if [[ ${BRANCH_EXIT_STATUS} != 0 ]]; then
-  echo "Unable to push current branch to Github origin."
-  exit ${BRANCH_EXIT_STATUS}
-fi
-
 # get the base of the github fork to issue a pr against
 GITHUB_FORK_BASE="$(echo "${ORIGIN}" | sed 's/\/.*//')"
 if [[ -z "${GITHUB_FORK_BASE}" ]]; then
   echo "Unable to determine fork of remote repo."
-  exit 1
-fi
-
-# get the github token
-GITHUB_TOKEN="$(git hub-token)"
-if [[ $? != 0 ]]; then
-  echo "Github api token required."
   exit 1
 fi
 
@@ -68,6 +53,21 @@ if [[ "${UPSTREAM_HOST}" != *github.com ]]; then
   GITHUB_API_BASE="${UPSTREAM_HOST}/api/v3"
 fi
 
+# get the github token
+GITHUB_TOKEN="$(git hub-token "$UPSTREAM_HOST")"
+if [[ $? != 0 ]]; then
+  echo "Github api token required."
+  exit 1
+fi
+
+# push this branch to origin first
+git push origin "${BRANCH}"
+BRANCH_EXIT_STATUS=$?
+if [[ ${BRANCH_EXIT_STATUS} != 0 ]]; then
+  echo "Unable to push current branch to Github origin."
+  exit ${BRANCH_EXIT_STATUS}
+fi
+
 PR_RESPONSE=$(curl \
   -H "Authorization: token ${GITHUB_TOKEN}" \
   "https://${GITHUB_API_BASE}/repos/${UPSTREAM}/pulls" \
@@ -77,7 +77,7 @@ CURL_EXIT_CODE=$?
 
 # output result to std error
 if getopt_assert -v:--verbose "$@"; then
-  echo "${PR_RESPONSE}" > /dev/stderr
+  echo "${PR_RESPONSE}" >&2
 fi
 
 URL_EXPR="$(echo "${PR_RESPONSE}" | grep '^  "html_url": "')"
diff --git a/dotenv/bin/git-hub-token b/dotenv/bin/git-hub-token
--- a/dotenv/bin/git-hub-token
+++ b/dotenv/bin/git-hub-token
@@ -1,47 +1,70 @@
-#!/bin/sh
+#!/bin/bash
 # Retieve a github token if not already generated
 # To get the token: curl -i https://api.github.com/authorizations -u "GITHUB_USERNAME_HERE" -d '{"scopes":"repo","note":"GITHUB_TOKEN_NAME"}'
+set -x
+
+REUSE_EXISTING=1
+if [[ "$1" == "-n" ]]; then
+  REUSE_EXISTING=0
+  shift
+fi
+
+# check if we want the token from github
+UPSTREAM_HOST="github.com"
+if [[ -n "$1" && "$1" != *github.com ]]; then
+  UPSTREAM_HOST="$1"
+fi
 
 # if the -n flag is passed in, don't use the local store, just generate a new token
-if [ "$1" != "-n" ]; then
+if [[ "${REUSE_EXISTING}" == 1 ]]; then
   # check the environment first
-  if [ -n "$GIT_HUB_API_TOKEN" ]; then
+  if [[ "${UPSTREAM_HOST}" == *github.com ]] && [[ -n "$GIT_HUB_API_TOKEN" ]]; then
     echo "$GIT_HUB_API_TOKEN"
     exit 0
   fi
   # then check the gitconfig file
-  EXISTING_TOKEN=$(git config --get github.apitoken)
-  if [ -n "$EXISTING_TOKEN" ]; then
+  if [[ "${UPSTREAM_HOST}" != "github.com" ]]; then
+    EXISTING_TOKEN=$(git config --get "github.apitoken")
+  else
+    EXISTING_TOKEN=$(git config --get "github.${UPSTREAM_HOST}.apitoken")
+  fi
+  if [[ -n "$EXISTING_TOKEN" ]]; then
     echo "$EXISTING_TOKEN"
     exit 0
   fi
 fi
 
+# password auth via curl not available for most github enterprise setups
+if [[ "${UPSTREAM_HOST}" != *github.com ]]; then
+  echo "Github Enterprise token creation is not supported" >&2
+  exit 1
+fi
+
 # Generate a token for the following username
 read -p "Github username: " GITHUB_USERNAME
-if [ -z "$GITHUB_USERNAME" ]; then
-  echo "Github username required"
+if [[ -z "$GITHUB_USERNAME" ]]; then
+  echo "Github username required" >&2
   exit 1
 fi
 
 HOSTNAME=$(hostname)
 # Grab the app token name, using hostname as the default
 read -p "Github token name ($HOSTNAME): " GITHUB_TOKEN_NAME
-if [ -z "$GITHUB_TOKEN_NAME" ]; then
+if [[ -z "$GITHUB_TOKEN_NAME" ]]; then
   GITHUB_TOKEN_NAME="$HOSTNAME"
 fi
 
 GITHUB_TOKEN_RESPONSE=$(curl -i https://api.github.com/authorizations -u "$GITHUB_USERNAME" -d '{"scopes":"repo","note":"'$GITHUB_TOKEN_NAME'"}')
 
-if [ -z "$GITHUB_TOKEN_RESPONSE" ]; then
+if [[ -z "$GITHUB_TOKEN_RESPONSE" ]]; then
   exit 1
 fi
 
 # output the curl request to stderr
-echo $GITHUB_TOKEN_RESPONSE > /dev/stderr
+echo $GITHUB_TOKEN_RESPONSE >&2
 
 # If the response doesn't contain a token then exit with an error
-if [ -z "$(echo "$GITHUB_TOKEN_RESPONSE" | grep '"token":')" ]; then
+if [[ -z "$(echo "$GITHUB_TOKEN_RESPONSE" | grep '"token":')" ]]; then
   exit 1
 fi
 
@@ -51,8 +74,8 @@ GITHUB_TOKEN=$(echo "$GITHUB_TOKEN_RESPONSE" | grep '"token":' | sed 's/  *"toke
 echo "$GITHUB_TOKEN"
 
 # Write the token to the user's git config
-if [ "$1" != "-n" ]; then
-  git config --global github.apitoken "$GITHUB_TOKEN"
+if [[ "${REUSE_EXISTING}" == 1 ]]; then
+  git config --file ~/.gitconfig.local github.apitoken "$GITHUB_TOKEN"
 fi
 
 exit 0
